services:
  wg-easy:
    image: weejewel/wg-easy
    container_name: wg-easy
    environment:
      - WG_HOST=${WG_HOST}
      - PASSWORD=${PASSWORD}
      - WG_PORT=${WG_PORT:-51820}
    volumes:
      - ./wg-data:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv6.conf.all.forwarding=1
    restart: unless-stopped
    networks:
      - wgnet
    dns:
      - 1.1.1.1
      - 8.8.8.8

networks:
  wgnet:
    external: true
