name: Deploy VPN to VPS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo "WG_HOST=${{ secrets.VPN_WG_HOST }}" >> .env
          echo "PASSWORD=${{ secrets.VPN_PASSWORD }}" >> .env
          echo "WG_PORT=${{ secrets.VPN_PORT || '51820' }}" >> .env

      - name: Copy files to VPS
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_DEPLOY_KEY }}
          source: ".env,docker-compose.yml"
          target: "~/projects/vpn"

      - name: Restart VPN service on VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_DEPLOY_KEY }}
          script: |
            cd ~/projects/vpn
            docker compose pull
            docker compose up -d
